name: Code Review

on: [ pull_request ]

jobs:
  codecov:
    runs-on: ubuntu-latest

    env:
      ADMOB_ID_DEV: ${{ secrets.ADMOB_ID_DEV }}
      ADMOB_ID_BANNER_DEV: ${{ secrets.ADMOB_ID_BANNER_DEV }}
      ADMOB_ID_PROD: ${{ secrets.ADMOB_ID_PROD }}
      ADMOB_ID_BANNER_PROD: ${{ secrets.ADMOB_ID_BANNER_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create config.properties file
        run: |
            echo "ADMOB_ID_DEV=${ADMOB_ID_DEV}" > $GITHUB_WORKSPACE/config.properties
            echo "ADMOB_ID_BANNER_DEV=${ADMOB_ID_BANNER_DEV}" >> $GITHUB_WORKSPACE/config.properties
            echo "ADMOB_ID_PROD=${ADMOB_ID_PROD}" >> $GITHUB_WORKSPACE/config.properties
            echo "ADMOB_ID_BANNER_PROD=${ADMOB_ID_BANNER_PROD}" >> $GITHUB_WORKSPACE/config.properties

      - name: Build and test
        run: ./gradlew clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml